Fix docker-compose local unit-test, minor cleanup
Unfortunately the "unit-test" isn't much of a unit test, clearly connecting to the database containers...
... but after these changes, it at least starts up on my machine, and doesn't collide with other instances / port use / etc.
It also finally connects to postgres, though that should still be fixed eventually.

To summarize the changes:
- `ports` -> `expose` to keep networking internal.  ports are no longer publicly mapped, so you can run other things without colliding.
- `command` array -> a string.  because wow was that verbose.
- adding postgres connection info to unit-test, as it was using the wrong host + username previously.

---

Unfortunately tests still don't pass locally, I have not yet traced down the reason.
They stop here for me, on a few errors like this:
```
--- FAIL: TestSQLHistoryV2PersistenceSuite (3.70s)
    --- PASS: TestSQLHistoryV2PersistenceSuite/TestConcurrentlyCreateAndAppendBranches (1.23s)
    --- FAIL: TestSQLHistoryV2PersistenceSuite/TestConcurrentlyForkAndAppendBranches (0.61s)
        historyV2PersistenceTest.go:752:
            	Error Trace:	historyV2PersistenceTest.go:752
				historyV2PersistenceTest.go:570
				asm_amd64.s:1357
            	Error:      	Expected nil, but got: &types.InternalDataInconsistencyError{Message:"corrupted history event batch, eventID is not continouous"}
            	Test:       	TestSQLHistoryV2PersistenceSuite/TestConcurrentlyForkAndAppendBranches
```